### ISSUE TITLE
청원 리스트와 청원 세부 화면

### ISSUE THREAD

**Issue by hyunmin0317** [hyunmin0317/SMU-Petition-FE#6]
- [x] post_list
    - [x] post_list.html
    - [x] post_list.css
- [x] post_detail
    - [x] post_detail.html
    - [x] post_detail.css

**Comment by yeopyeop-82** [comment]
post_list.html / post_list.css 구성 완료 했습니다.
또한 개발 환경도 조금 더 정리했어요.
내용 발표는 내일 하겠습니다.

post_list 까지 하고 잠시 멈췄는데요, 사유는 이것저것 통일하고 정해야할 규칙이 있어야 할 것 같아서 입니다..
아래 적힌 내용이 통일 되면 나머지 빠르게 구성해보도록 할게요.

개발 환경을 조금 더 정리 했는데, 내일 프론트 회의때 어떻게 정리했는지 발표할게요.
CSS 파일이 흩어져 있는것을 개인적으로 선호하지 않아서,
styles.css 파일을 만들고 거기에 한번에 import 후, html 파일에 styles.css 파일만 link 했습니다.
혹시 기존 방법이 더 편하면 그걸로 가면 될 것 같습니다.

class 이름 짓는것도 통일해야 할 것 같아요.
BEM 네이밍으로 통일하면 좋을 것 같습니다. 현업에서도 BEM 네이밍 많이 사용하니까요 !
참고 링크 : https://velog.io/@nemo/bem

구성 내용 -
게시판 구성 (nav_bar, footer 자리 제외)
-> tbody에 hover transition 설정 등
변수 설정 (학교 색 (--sangmyung))
글꼴 설정 (구글 폰트 - 나눔고딕)

Q. 왜 include-html이 작동하지 않을까요? 그냥 tr 태그를 가져와서 붙이는 식으로 해결하긴 했습니다만..

!. Bootstrap 덕분에 테이블의 body 가 display: table-row 의 속성을 가지는데요, 이 display 속성은 padding을 가질 수 없더라구요. tr 안에 있는 td elements에 padding을 주는 식으로 우회하면 padding 적용이 가능합니다. 단, td의 first-child에는 예외를 줘야 해요. 따로 적용해야합니다. 왜 그런지는 아직 모르겠어요,..
https://stackoverflow.com/questions/3656615/padding-a-table-row

https://user-images.githubusercontent.com/61226778/213197197-5956e8b4-f5c5-4f47-aac0-cbd0abe32a29.mov

**Comment by yeopyeop-82** [comment]
Q. 왜 include-html이 작동하지 않을까요? 그냥 tr 태그를 가져와서 붙이는 식으로 해결하긴 했습니다만..

A. 서버 문제였어요 . 보안상의 문제인듯 합니다. 로컬로 열면 javascript에 문제가 생기더라구요. 해결방법은 VSCode 에서는 Open with Live Server 클릭 / 파이참에서 열기 방법으로 해결 가능해요 .

**Comment by yeopyeop-82** [comment]
수정사항 1번 : navbar sticky 
- 별로 중요한 수정사항은 아닙니다. navbar가 사라지는 것이 싫어서 이미지 스크롤이 끝날때 까지 fix 되어있다가 추후 이미지와 함께 자연스럽게 스크롤 되면서 사라질 수 있도록 sticky 처리 하였습니다.

https://user-images.githubusercontent.com/61226778/213253970-87102774-d02d-4f4d-be7e-b5189e5628e4.mov

**Comment by yeopyeop-82** [comment]
수정사항 2번 ** 중요 : post_list 디자인 수정
- 청원 검색하기와 청원 등록하기가 가장 주요한 기능인 화면입니다.
- 즉 이 두가지 기능에 접근성이 좋아야 한다는 이야기이지요.
- 그 결과로 가독성이 좋게 h1 크기로 크게 글씨를 키워 버튼과 문구를 배치했어요.
- n개의 청원과 n개의 답변은 지스트 청원에서 따왔습니다.
- 이 디자인은 어디서 따온 것이 아닌 제가 직접 구성한거라 딱히 어디 겹치는 곳이 없어서 독창성이 있을 것 같습니다. 하지만 검증되지 않아 여러분이 보시기에 구릴 수 있으니 피드백/검토 부탁드려요 !

청원 검색하기
- 버튼을 누르면 자동으로 input form으로 focus 될 수 있도록 처리하였습니다.
- 따로 검색창을 만드는 것보다 존재하는 component를 사용하는 것이 좋을 것 같아서 이렇게 처리해봤어요

이런 청원은 삭제/숨김 또는 반려처리 될 수 있습니다.
- 음.. 고민을 많이 했던 지점입니다. 아코디언으로 처리할까? 토글로? 아니면 navbar를 하나 더 갖다 붙일까?
- 부트스트랩 컴포넌트 설명 페이지를 모두 뒤져본 결과.. 오프 캔버스 방식이 적절한 듯 하여 이렇게 해 보았습니다.
- 아직 확정을 지은 부분은 아니라 내용은 안 넣었구요. 저는 괜찮은 것 같은데 다른사람이 보기에는 이상할 수 있으므로.. 검토 부탁드립니다.

https://user-images.githubusercontent.com/61226778/213255500-a48f0dcc-958b-452f-85d1-e1e38df12f84.mov


디자인은 제가 생각하기에 괜찮은게 다가 아니기에,, 중간중간 계속 피드백을 받도록 하겠습니다. 집단지성이 필요해요 !

**Comment by yeopyeop-82** [comment]
디자인 괜찮은 것 같으면 트랜지션 효과 및 내용 추가로 조금 더 다듬어서 post_list 마무리 짓도록 하겠습니다 !

**Comment by hyunmin0317** [comment]
저는 디자인도 너무 마음에 들고 sticky와 트랜지션 효과도 들어가서 사용자분들이 더 편리하게 사용할 수 있을거 같아용!
승엽아 정말 수고많았어😍

**Comment by yeopyeop-82** [comment]
https://user-images.githubusercontent.com/61226778/216270993-28addf86-d3d3-423c-a4e5-5a848aa8045f.mov

**Comment by yeopyeop-82** [comment]
post_detail 구성
- gist의 청원페이지를 '많이' 참고했습니다.ㅎㅎ
- 색을 좀 더 넣으면 좋을까요? 구성은 괜찮으나 뭔가 비어보이는 느낌이 듭니다. 강조 색이 없어서 그런것 같아요
- 버튼의 색을 넣거나, border의 색을 좀더 진하게 주면 어떨까요?
- 지금 보니 버튼의 크기도 좀 더 키우면 좋을 것 같습니다.

Q. 모든 웹 브라우저의 기본 확대값인 125%에서 페이지가 너무 확대되어 보입니다. 75%정도에서 페이지가 예쁘게 보이는데, 혹시 이렇게 전체 사이즈를 줄일 수 있나요?
